version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]

  frontend:
    build: ./data_annotator
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always