version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build: ./data_annotator
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always