name: data_annotator
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  bounding_box_annotation: ^0.1.2
  dio: ^5.8.0+1
  file_picker: ^9.2.1
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.3.0
  vector_math: ^2.1.4
  web_socket_channel: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
